#!/bin/bash
# ==========================================


cd /usr/bin
rm -rf restart
rm -r restart
rm restart
rm -r sslh-fix-reboot
rm -rf sslh-fix-reboot
rm sslh-fix-reboot

cd /usr/bin
wget -O sslh-fix-reboot "https://raw.githubusercontent.com/presult77/narassh/master/sslh/sslh-fix-reboot.sh"
wget -O sslh-fix-bug "https://raw.githubusercontent.com/presult77/narassh/master/sslh/sslh-fix-bug.sh"
wget -O restart "https://raw.githubusercontent.com/presult77/narassh/master/ssh/restart.sh"

cd /usr/bin
chmod +x sslh-fix-reboot
chmod +x sslh-fix-bug
chmod +x restart

cd /root/
# nano /etc/rc.local
cat > /etc/rc.local <<-END
#!/bin/sh -e
# rc.local
# By default this script does nothing.

sslh-fix-reboot
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
exit 0
END

# Ubah izin akses
chmod +x /etc/rc.local

# enable rc local
systemctl enable rc-local
systemctl start rc-local.service

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

cd /root/
